Woodcutting: Tree Compactor
Mykindos/BetterPvP pull request #1058
Opened 2024-09-15 03:16 UTC by 8SIXSect

## Describe your changes
- This perk gives the player access to the `/treecompactor` command
- `This command turns a stack of any log into a **Compacted Log**
- **Compacted Logs** can be sold at chops for the same price a stack of logs would be sold for
- **Purpose** - One of the biggest complaints about Fishing, *I heard* & experienced, in the **Alpha** was that player's inventories filled up too fast with Fish. This perk doesn't address that but the same problem is bound to happen with Woodcutting so this serves to prevent that
- [Demo](https://imgur.com/a/0fUEjZi)

## Link to issue (if applicable)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

2024-09-15 03:40 UTC, ezrn commented
should add this to fishing too fr

2024-09-16 03:01 UTC, 8SIXSect commented
fr

2024-09-27 02:38 UTC, Mykindos requested changes

2024-09-27 02:38 UTC, Mykindos commented on progression/src/main/java/me/mykindos/betterpvp/progression/profession/woodcutting/commands/TreeCompactorCommand.java
> +                itemHandler.updateNames(itemStack);
You shouldn't need the second line here

2024-10-05 04:48 UTC, Mykindos requested changes

2024-10-05 04:48 UTC, Mykindos commented on core/src/main/java/me/mykindos/betterpvp/core/command/Command.java
> +
Should not go here, you can override the procesTabComplete in individual commands, e.g. CustomEffectSubCommand.java

2024-10-05 04:48 UTC, Mykindos commented on core/src/main/java/me/mykindos/betterpvp/core/command/ICommand.java
> +        LOG_TYPES,
Same deal

2024-10-05 04:48 UTC, Mykindos commented on progression/src/main/java/me/mykindos/betterpvp/progression/profession/skill/woodcutting/TreeCompactor.java
> +        if (!event.getBlock().getType().equals(Material.OAK_WOOD)) return;
Youl want to add a check here for client administration mode, we wouldnt want to stop admins from placing them

client#isAdministrating()

2024-10-05 04:48 UTC, Mykindos commented on progression/src/main/resources/progression-migrations/V2__Create_items.sql
> +INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('OAK_WOOD', 'progression', 'compacted_log', '<light_purple>Compacted Log', 0, 1, 0);
This is my fault for taking so long to review, but could you please create a new migration sql file, e.g.

V3__Create_compacted_log_item.sql
and insert this line in there instead?

Same goes for the shop item migration script

2024-10-05 04:50 UTC, Mykindos commented on progression/src/main/resources/progression-migrations/V2__Create_items.sql
> +INSERT IGNORE INTO items (Material, Namespace, Keyname, Name, ModelData, Glow, hasUUID) VALUES ('OAK_WOOD', 'progression', 'compacted_log', '<light_purple>Compacted Log', 0, 1, 0);
Maybe even like V2.001_blahblahblah.sql would work since its such a small change

2024-10-22 13:05 UTC, Mykindos approved these changes

2024-10-22 13:06 UTC, merged