Storm sphere
Mykindos/BetterPvP pull request #1102
Opened 2024-10-15 05:23 UTC by expires

## Describe your changes
ezrn

## Link to issue (if applicable)
#ezrn

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

2024-10-15 05:27 UTC, StudentAlleg requested changes
Nothing is done using the config, which should follow how other skills use the config and methods.

2024-10-15 05:27 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +                "anyone hit for  +  seconds",
No values here

2024-10-15 05:27 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +            if (UtilTime.elapsed(duration, (long) 3 * 1000)) {
Should be a config value

2024-10-15 05:27 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +            for (LivingEntity target : UtilEntity.getNearbyEnemies(player, location, 6.0)) {
Should be a config value

2024-10-15 05:27 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +                championsManager.getEffects().addEffect(target, player, EffectTypes.SHOCK, 50L);
Config value

2024-10-15 05:27 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +                championsManager.getEffects().addEffect(target, EffectTypes.SILENCE, 50L);
config value

2024-10-15 05:27 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +        target.getWorld().strikeLightning(target.getLocation());
is this intended to do damage? Lightning does not deal damage in BetterPvP

2024-10-23 04:05 UTC, StudentAlleg requested changes
I'm trying to think of a better way to word the description, but not really thinking of anything. It pulses from where the arrow hits (which means it doesn't need to actually hit a player), which isn't as clear as I'd like it to be.

2024-10-23 04:05 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +                "Shoot a storm arrow that <effect>Silences</effect> and <effect>Cripples</effect> ",
Should be Shocks instead of cripples (cripples is not a status effect).

2024-10-24 12:37 UTC, Mykindos requested changes

2024-10-24 12:37 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +import org.bukkit.*;
wildcard, disable in intellij

2024-10-24 12:37 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +import java.util.*;
.

2024-10-24 12:37 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +    private final HashMap<Player, StormData> activeSpheres = new HashMap<>();
WeakHashMap

2024-10-28 07:40 UTC, Mykindos requested changes

2024-10-28 07:40 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +import java.util.*;
how can you mark something as resolved when u didnt even fix it bud

2024-10-28 07:40 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/bow/StormSphere.java
> +import java.util.*;
disable it in intellij

2024-10-28 08:22 UTC, Mykindos approved these changes

2024-10-28 08:22 UTC, merged