Fix deflection base charges
Mykindos/BetterPvP pull request #1261
Opened 2024-11-14 00:07 UTC by StudentAlleg

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes.

2024-11-14 00:07 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Deflection.java
> +@Slf4j
```suggestion
```

2024-11-14 00:08 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Deflection.java
> +import lombok.extern.slf4j.Slf4j;
```suggestion
```

2024-11-14 09:09 UTC, Mykindos requested changes

2024-11-14 09:09 UTC, Mykindos commented on champions/src/main/resources/configs/skills/skills.yml
> +      maxlevel: 5
passives have a max rank of 3

2024-11-14 23:42 UTC, StudentAlleg commented on champions/src/main/resources/configs/skills/skills.yml
> +      maxlevel: 5
oops, dont know why that was there

2024-11-15 11:13 UTC, Mykindos approved these changes

2024-11-15 11:13 UTC, merged