Add water block tip
Mykindos/BetterPvP pull request #1304
Opened 2024-11-19 05:34 UTC by StudentAlleg

Fixes #1225

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

2024-11-19 13:24 UTC, Mykindos approved these changes

2024-11-19 13:24 UTC, Mykindos requested changes

2024-11-19 13:24 UTC, Mykindos commented on clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanWaterBlockTip.java
> +@Slf4j
old logging

2024-11-20 08:32 UTC, StudentAlleg commented on clans/src/main/java/me/mykindos/betterpvp/clans/tips/tips/ClanWaterBlockTip.java
> +import lombok.extern.slf4j.Slf4j;
```suggestion
```

2024-11-20 14:50 UTC, Mykindos approved these changes

2024-11-20 14:50 UTC, merged