vengeance ability
Mykindos/BetterPvP pull request #20
Opened 2023-09-22 19:46 UTC by ezrn

2023-09-22 20:13 UTC, StudentAlleg requested changes
numHits is not implemented correctly. Is this supposed to be the maximum number of hits, a tracker of hits (in which case do not retrieve it from config), or global hits (in which case it is implemented correctly)?

There does not appear to be a cap for numHits.

2023-09-22 20:13 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
> +    private int numHits;
Num hits is never retrieved. Needs to override loadSkillConfig: `@Override
    public void loadSkillConfig(){
        numHits= getConfig("numHits", 3, Integer.class);
    }`

2023-09-22 20:13 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
> +        return new String[]{
No usage of numHits in desciption.

2023-09-22 20:13 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
> +    private int numHits;
Does not apply if this is not the maximum hits this skill applies for.

2023-09-22 20:13 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
> +        return new String[]{
Does not apply if this is not the maximum hits this skill applies for.

2023-09-23 04:31 UTC, StudentAlleg reviewed
Skill increases damage per hit per player, resseting if damage is taken from any source.

2023-09-23 04:31 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/knight/passives/Vengeance.java
> +                "For every subsequent hit, your damage will increase by <val>" + (level * 0.25) +"</val>",
Should probably have damage increase in config.

2023-09-23 04:32 UTC, StudentAlleg approved these changes

2023-09-28 19:29 UTC, Mykindos commented
too similar to repeated strikes

2023-09-29 05:28 UTC, closed without merging