made flesh hook function similarly to mineplex
Mykindos/BetterPvP pull request #246
Opened 2023-12-16 20:20 UTC by ezrn

- Now only shoot one hook instead of 5
- Now does damage which scales based on level and the amount the hook was charged
- Everything else remains the same

2023-12-18 01:38 UTC, StudentAlleg requested changes

2023-12-18 01:38 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/FleshHook.java
> +                "and dealing up to <val>" + (damage + (damageIncreasePerLevel * (level-1)))+"</val> damage",
This should be in a separate function just for ease of maintaining the file.

2023-12-18 01:38 UTC, StudentAlleg commented on core/src/main/java/me/mykindos/betterpvp/core/combat/throwables/ThrowableItem.java
> +    public void setChargePercent(int chargePercent) {
I don't understand why you are doing this here, and not keeping it contained in FleshHook. Whenever you shoot a fleshhook, you should be able to keep track of it in a WeakHashmap, and on checking for collision you check to see if that fleshhook is in your list.

2023-12-24 14:03 UTC, Mykindos approved these changes

2023-12-24 14:16 UTC, merged