Add crafting system
Mykindos/BetterPvP pull request #256
Opened 2023-12-20 00:53 UTC by StudentAlleg

#160 - Allow for the easy(ish) creation of crafting recipes, and a system to prevent unwanted recipes.

- [ ] Block specified recipes from config
- [ ] Easy implementation of recipes in code

2023-12-29 05:27 UTC, StudentAlleg reviewed
Ready for review. I am planning on going over this in the coming days, as this has felt semi-spaghetti, but I first need to get a break from this specific code and come back to it with fresh eyes.

Features Include:

- Ability to disable recipes through config (crafting, smelting, anything that is a keyed recipe) 
- Ability to spawn custom items
- Reworked internal item handling, now goes by Namedspacedkey#asString()
- Added custom durability, items break after 0
- Standard item fields are defined in database, not in code
- Items that require a code component load standard item fields on runtime
- Custom/Overridden items consist of a Material +  CustomModelData. A custom item is defined by these things, all other aspects can be applied at different times.

2023-12-29 13:11 UTC, Mykindos requested changes

2023-12-29 13:11 UTC, Mykindos commented on core/src/main/java/me/mykindos/betterpvp/core/command/commands/admin/CustomGiveCommand.java
> +        }*/
remove?

2023-12-29 13:11 UTC, Mykindos commented on core/src/main/java/me/mykindos/betterpvp/core/items/BPVPItem.java
> +    public ItemStack damageItem (Player player, ItemStack itemStack, int damage) {
remove space after damageItem (

2023-12-30 06:57 UTC, Mykindos requested changes
Some things from a quick test:

- Log messages sent when breaking a block can be removed (probably sends it in other situations as well)
- Damage to armour should probably just be kept to 1, instead of the damage dealt. Keeps it in line with weapons and probably easier to balance later on.
- There is quite a few possible null pointer warnings around usage of dataContainer.get(CoreNamespaceKeys.DURABILITY_KEY, PersistentDataType.INTEGER)

    some of these seem to just be IDE having a spazm and likely would never cause issues, but warnings are an eye sore. I'd 
    recommend in some cases just doing get() and then checking if it is null instead of calling has
- I'd like to see if there is something we can do with the actual item durability to make it visible without needing to hover the item. Perhaps setting it to a percentage depending on the artificial durability. There may also be a way to change it without messing with the items vanilla durability at all. I don't expect you to do this as part of your PR, its something I would happily look into afterwards

2023-12-30 07:09 UTC, StudentAlleg commented
> Some things from a quick test:
> 
>     * Log messages sent when breaking a block can be removed (probably sends it in other situations as well)
> 
>     * Damage to armour should probably just be kept to 1, instead of the damage dealt. Keeps it in line with weapons and probably easier to balance later on.
> 
>     * There is quite a few possible null pointer warnings around usage of dataContainer.get(CoreNamespaceKeys.DURABILITY_KEY, PersistentDataType.INTEGER)
>       some of these seem to just be IDE having a spazm and likely would never cause issues, but warnings are an eye sore. I'd
>       recommend in some cases just doing get() and then checking if it is null instead of calling has
> 
>     * I'd like to see if there is something we can do with the actual item durability to make it visible without needing to hover the item. Perhaps setting it to a percentage depending on the artificial durability. There may also be a way to change it without messing with the items vanilla durability at all. I don't expect you to do this as part of your PR, its something I would happily look into afterwards

1. Fixed
2. Changed, makes sense
3. It shouldn't ever get a null pointer because it is always checked, but I think I am going to move some of those functions into UtilItem
4. Yeah, I was thinking about that. Probably will end up setting damage based on the ration of custom durability/maxDurability. But could be confusing with the numbers, wonder if that is hideable

2024-01-01 06:25 UTC, Mykindos approved these changes

2024-01-01 06:25 UTC, merged