Whirlwind Sword
Mykindos/BetterPvP pull request #368
Opened 2024-01-15 02:23 UTC by ezrn

2024-01-24 05:52 UTC, Mykindos requested changes
also post a video of it

2024-01-24 05:52 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/WhirlwindSword.java
> +        baseDamage = getConfig("damage", 3.0, Double.class);
keep variable name inline with config name, i.e. baseDamage = getConfig("baseDamage"

2024-01-24 06:51 UTC, ezrn commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/sword/WhirlwindSword.java
> +        baseDamage = getConfig("damage", 3.0, Double.class);
fixed

2024-01-27 05:41 UTC, Mykindos approved these changes

2024-01-27 05:51 UTC, closed without merging