new archery ability for assassin
Mykindos/BetterPvP pull request #4
Opened 2023-09-19 07:13 UTC by ezrn

2023-09-19 07:18 UTC, Mykindos requested changes

2023-09-19 07:18 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Archery.java
> +    @EventHandler(priority = EventPriority.HIGHEST)
event priority should probably be medium or high

2023-09-19 07:18 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Archery.java
> +
idiot

2023-09-20 04:24 UTC, 0-Mqix commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/passives/Archery.java
> +
LMAO

2023-09-20 04:54 UTC, closed without merging