Skill Feedback + Effect on LivingEntity
Mykindos/BetterPvP pull request #467
Opened 2024-01-29 07:26 UTC by StudentAlleg

Fixes #437

2024-02-01 16:48 UTC, Mykindos requested changes

2024-02-01 16:48 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/StrengthInNumbers.java
> +        championsManager.getEffects().addEffect(player, EffectType.STRENGTH, strengthStrength, (long) (getDuration(level) * 1000L));
strengthLevel or strengthAmplifier plz

2024-02-02 01:03 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/brute/axe/StrengthInNumbers.java
> +        championsManager.getEffects().addEffect(player, EffectType.STRENGTH, strengthStrength, (long) (getDuration(level) * 1000L));
as though commands

2024-02-03 13:13 UTC, Mykindos approved these changes

2024-02-03 13:13 UTC, merged