Tips
Mykindos/BetterPvP pull request #52
Opened 2023-09-28 03:59 UTC by StudentAlleg

Framework for adding a chat Tip system.

Currently sends a message to players not in a Clan that they can join a Clan. 

Plans to expand include added a toggle in settings (partially setup), other tip information.

2023-09-28 04:31 UTC, Mykindos requested changes

2023-09-28 04:31 UTC, Mykindos commented on clans/src/main/java/me/mykindos/betterpvp/clans/clans/tips/TipEvent.java
> +    }
You dont need this if you put @Data annotation on the TipEvent

2023-09-28 04:31 UTC, Mykindos commented on clans/src/main/java/me/mykindos/betterpvp/clans/clans/tips/TipListener.java
> +        gamerManager.getObjectsValues().forEach(gamer -> {
for(Player player : Bukkit.getOnlinePlayers()) {
    gamerManager.getObject(player.getUniqueId()).ifPresent(gamer -> {
        // tip logic
    });
}

2023-09-28 04:31 UTC, Mykindos commented on core/src/main/java/me/mykindos/betterpvp/core/gamer/GamerManager.java
> +    public Collection<Gamer> getObjectsValues() {
Collection<?> getObjectsValues() 

in Manager.java

2023-09-28 04:33 UTC, Mykindos approved these changes

2023-09-28 04:33 UTC, Mykindos commented on clans/src/main/java/me/mykindos/betterpvp/clans/clans/tips/TipListener.java
> +    @EventHandler
@EventHandler (priority = EventPriority.MONITOR)

Also check at the start of the method if event.isCancelled()

2023-09-28 04:59 UTC, StudentAlleg commented
Updated

2023-09-28 22:28 UTC, StudentAlleg commented
Updated framework to use Enums. This is kind of how I want to do things, but I am looking to refactor into a weighted list format to allow for semi-random choice of what tip to send.

2023-09-29 19:16 UTC, StudentAlleg commented
Rebased in preparation for review.

2023-09-29 19:18 UTC, StudentAlleg reviewed
Ready for Review. Changes: Tips are now stored in Enums (is this too much). Implemented WighedList via TipList for easily handling inserting tips. Added hover and click events.

2023-09-30 03:20 UTC, StudentAlleg commented
![tips](https://github.com/Mykindos/BetterPvP/assets/36683605/951f74b3-7417-4441-af07-2ebaa2ac133c)

2023-09-30 07:00 UTC, Mykindos commented
It looks ok, though I'm not sure if enum is the right choice. You could go down the road of creating a seperate object for each tip and give each of them their own predicate. That way in the tip event you wouldn't need to check a bunch of different conditions manually, would make adding new tips a bit easier

2023-10-01 01:14 UTC, StudentAlleg reviewed
Changed Tips to be implemented similarly to how skills are. There are probably improvements like predicates, but I am not completely sure how to use them. 

It should be much easier to add new skills.

2023-10-01 01:14 UTC, StudentAlleg commented
Also cleaned up and removed a lot of added files that turned out to be unnecessary with this implementation

2023-10-01 05:35 UTC, StudentAlleg reviewed
Moving Tips to core per feedback.

2023-10-02 03:38 UTC, StudentAlleg reviewed
Tried changing to a loader style, didn't work. https://github.com/StudentAlleg/BetterPvP/tree/student/tip-loader

Works as is.

2023-10-02 07:37 UTC, Mykindos approved these changes

2023-10-02 07:37 UTC, merged