made bulls charge like mineplex + hilt and sever fixes
Mykindos/BetterPvP pull request #526
Opened 2024-02-08 06:44 UTC by ezrn

- User can now take knockback while charging, but now deals no knockback against the target for the duration
- Fixed sever and hilt smash sounds + logic

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have tested my changes.

2024-02-08 06:51 UTC, StudentAlleg commented
not taking knockback allows for the knight to engage, especially against targets that it could struggle against (i.e. a medium range ranger). Yes, you could take kb on Mineplex, but I think not taking kb fits more than not dealing kb.

2024-02-08 07:18 UTC, ezrn commented
> not taking knockback allows for the knight to engage, especially against targets that it could struggle against (i.e. a medium range ranger). Yes, you could take kb on Mineplex, but I think not taking kb fits more than not dealing kb.

bulls charge was designed to catch up to people, not dealing knockback allows it to cath up and deal significant damage to playres without them able to run away

2024-02-10 10:08 UTC, Mykindos commented
good luck killing a ranger with knight

2024-02-10 19:56 UTC, StudentAlleg commented
Could add it as a config option, that at least gives it an easy way to test (something like deals knockback while charging, takes knockback while charging), probably a double/100 tho

2024-02-10 23:13 UTC, ezrn commented
> good luck killing a ranger with knight

you cant do this anyways

2024-02-11 01:52 UTC, ezrn commented
anyways youre probobly right, ill revert it

2024-02-13 14:07 UTC, Mykindos requested changes

2024-02-13 14:07 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Sever.java
> +        return cooldown - cooldownDecreasePerLevel;
not how its calculated

should be cooldown - ((level - 1) * cooldownDecreasePerLevel)

2024-02-14 09:13 UTC, Mykindos approved these changes

2024-02-14 09:13 UTC, merged