many fixes
Mykindos/BetterPvP pull request #545
Opened 2024-02-11 01:49 UTC by ezrn

- Bulls charge end message playing 1 second after it actually expired
- Bulls charge particles being wrong
- Added end message to all skills that didn't have them(excessive force, hold position)
- Fixed fail messages for evade and disengage
- Fixed excessive force updateEvent running on the wrong frequency
- Gave smoke bomb a better visual for the user

2024-02-15 05:50 UTC, Mykindos commented
@ezrn is thise smoke bomb change the same as your other PR?

2024-02-15 06:29 UTC, ezrn commented
> @ezrn is thise smoke bomb change the same as your other PR?

I just removed it from this one, could create a merge conflict when you merge the other one but ill fix it when it does

2024-02-18 14:58 UTC, Mykindos requested changes

2024-02-18 14:58 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/ranger/sword/Disengage.java
> +            UtilMessage.message(player, getClassType().getName(), UtilMessage.deserialize("You failed <green>%s %d</green>", getName(), getLevel(player)));
You dont need UtilMessage.deserialize if you just make it Utilmessage.simpleMessage at the start

2024-02-19 00:34 UTC, Mykindos requested changes

2024-02-19 00:34 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Evade.java
> +                        UtilMessage.simpleMessage(player, getClassType().getName(),"You failed <green>%s %d</green>", getName(), getLevel(player));
we already have a level variable, no need for getLevel(player)

2024-02-20 13:06 UTC, Mykindos approved these changes

2024-02-20 13:07 UTC, merged