Void mage fix
Mykindos/BetterPvP pull request #554
Opened 2024-02-12 09:21 UTC by ezrn

- made void reduce energy based on damage dealt to the player isntead of per hit
- Fixes #538 

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have tested my changes.

2024-02-14 09:08 UTC, Mykindos requested changes

2024-02-14 09:08 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/passives/Void.java
> +                "reduced by <val" + getDamageReduction(level) + "</val> and drain <val>" + getEnergyReduction(level) + "</val> energy",
evidently untested

2024-02-15 05:32 UTC, Mykindos commented
you also forgot to mention you reduced the amount of energy void consumes by 85%

2024-02-15 05:39 UTC, ezrn commented
> you also forgot to mention you reduced the amount of energy void consumes by 85%

this is to account for the fact that every point of damage reduces energyReduction energy, where before it was every hit. This means that if someone deals 6 damage it will be 6 x energyReduction which is at base 6 x 3.0 = 18, where it was 20 per hit before. It is practically the same.

2024-02-15 06:09 UTC, Mykindos approved these changes

2024-02-15 06:10 UTC, merged