Vulnerability Changes
Mykindos/BetterPvP pull request #631
Opened 2024-02-27 07:46 UTC by ezrn

- After level 1(still 25% increase damage) it increases by 10% per level
- This allows variable levels of vulnerability to be used without being stuck with +50% increase or +25% increase, one of which is weak, and the other which is way too strong

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have tested my changes.

2024-02-29 11:26 UTC, Mykindos commented
Feel like you could just make it like strength, 1.5 damage per level

2024-03-01 23:58 UTC, StudentAlleg commented
> Feel like you could just make it like strength, 1.5 damage per level

That would be incredibly strong with low damage sources, as vulnerability applies to all damage.

2024-03-02 00:22 UTC, ezrn commented
> > Feel like you could just make it like strength, 1.5 damage per level
> 
> That would be incredibly strong with low damage sources, as vulnerability applies to all damage.

Inferno vulnerability would 1 shot brutes with a full burst

2024-03-02 06:38 UTC, ezrn commented
There may be a better way to do this, though I think percentages are the way to go. Maybe starting vulnerability at a lower value like 10%, and having it go up by 10% each time, then compensating any current abilities that use Vulnerability with these new levels. MArked for death for instance is pretty weak atm, whereas during season 1 of the 2020 wipe is was crazy broken. A system like this to give in between values would be very valuable.

2024-03-04 11:01 UTC, Mykindos commented
> There may be a better way to do this, though I think percentages are the way to go. Maybe starting vulnerability at a lower value like 10%, and having it go up by 10% each time, then compensating any current abilities that use Vulnerability with these new levels. Marked for death for instance is pretty weak atm, whereas during season 1 of the 2020 wipe it was crazy broken. A system like this to give in between values would be very valuable.

I guess since sword damage was decreased, marked for death lost value
I'm not opposed to making it 10% and moving marked for death up to Vuln 3 or 4

2024-03-04 11:06 UTC, Mykindos requested changes

2024-03-04 11:06 UTC, Mykindos commented on core/src/main/java/me/mykindos/betterpvp/core/effects/listeners/EffectListener.java
> +            double damageIncrease = 0.1 + (effect.getLevel() - 1) * 0.10;
because this isn't a vanilla effect, you shouldnt do -1

You could keep it the same as it was before but replace 0.25 with 0.10

2024-03-09 05:14 UTC, braulio-dev commented
Deferred until @Mykindos pushes effect system rework

2024-03-09 05:14 UTC, closed without merging