Update ice prison (and lightning orb sound)
Mykindos/BetterPvP pull request #681
Opened 2024-03-17 06:38 UTC by StudentAlleg

Add sounds on throw and travel from ice prison and lightning orb
Change ice prison to decay from top to bottom instead of all at once. The speed is now controlled by the variance variable

Fixes #612

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes.

2024-03-17 06:53 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
```suggestion
```

2024-03-17 07:24 UTC, Mykindos requested changes

2024-03-17 23:04 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
> +    }
Makes sense

2024-03-17 23:52 UTC, StudentAlleg commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
> +    }
implemented

2024-03-18 10:50 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/mage/axe/IcePrison.java
> +    }
good stuff

2024-03-18 10:50 UTC, merged