added RunedPickaxe
Mykindos/BetterPvP pull request #721
Opened 2024-05-01 07:19 UTC by manu10000

## Describe your changes
Added runed pickaxe

TODO: update lore and balance energy decrements 
## Link to issue (if applicable)
#623 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

2024-07-24 22:06 UTC, manu-y commented
Set the mining speed of the pickaxe to the same as a netherite pickaxe. not sure if you care about the pickaxe working on every block.

2024-07-26 13:50 UTC, Mykindos requested changes

2024-07-26 13:50 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/RunedPickaxe.java
> +        lore.add(Component.text("of mining any block instantly!", NamedTextColor.WHITE));
lore could probably be updated, ill let you cook

2024-08-19 14:15 UTC, Mykindos approved these changes

2024-08-19 14:15 UTC, merged