WIP: #417 - Fix movement legends
Mykindos/BetterPvP pull request #785
Opened 2024-05-31 23:57 UTC by bearloo

## Describe your changes
[Before](https://youtu.be/Rv4YYhUfX_c)
[After](https://youtu.be/g8aTTsNKnjo)

Updated movements to prevent canUse from removing players from the active set.
Since the player is still holding right click, the channel weapon check in [WeaponListener.java](https://github.com/Mykindos/BetterPvP/blob/master/core/src/main/java/me/mykindos/betterpvp/core/combat/weapon/listeners/WeaponListener.java) prevents them from becoming active again.

Relevant code from WeaponListener:

```
if (weapon instanceof ChannelWeapon channelWeapon) {
            if (clicked.get(event.getPlayer().getUniqueId()) == weapon) {
                return; // Skip if we're currently holding click on this weapon
            }

            if (channelWeapon.getEnergy() > 0) {
                if (!energyHandler.use(player, name, channelWeapon.getEnergy(), true)) {
                    return;
                }
            }

            clicked.put(player.getUniqueId(), weapon); // Log this weapon as clicked
}

if (weapon instanceof InteractWeapon interactWeapon) {
        interactWeapon.activate(player);
}
```

To-Do:
- [ ] Reduce the number of logs produced by `canUse()`
- [ ] Review gameplay change for Windblade, players can now fly out the of water if they enter swim mode

## Link to issue (if applicable)
#417

## Checklist before requesting a review
- [x ] I have performed a self-review of my code
- [x ] I have tested my changes.

2024-06-05 06:24 UTC, Mykindos commented
Will take a look at this after alpha finishes

2024-06-06 04:25 UTC, bearloo commented
Reverted non-gameplay-specific changes. 

Changes included are for: 
- Ensuring legends remain active if `canUse()` fails, fixes some issues seen where legends fail to activate 
- Only sending one usage notification if `canUse()` fails multiple times in a row, resets if the legend becomes inactive or `canUse()` succeeds

Let me know your suggestions for refactoring the code duplication. 

- The notification logic belongs in InteractWeapon but I can't change the interface to an abstract class without breaking inheritance, is something like an "InteractableChannelWeapon" that implements a ChannelWeapon and InteractWeapon interface a viable solution?
- There is a lot of duplicated pre-condition code for checking a legend hasn't become inactive that could get moved up into a parent class shared between all movement legends (or any ChannelWeapon legendary really)

2024-06-06 10:43 UTC, Mykindos requested changes

2024-06-06 10:43 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/WindBlade.java
> +    private final Set<UUID> activeUsageNotifications = new HashSet<>();
instead of creating this set for every ChannelWeapon, just created a protected set in ChannelWeapon itself

2024-06-11 12:42 UTC, merged