Notify users with sound when an ability has recharged
Mykindos/BetterPvP pull request #837
Opened 2024-06-04 11:35 UTC by manu10000

## Describe your changes
added a ping sound notification when abilities recharge. you're welcome jarif
## Link to issue (if applicable)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes.

2024-06-04 12:01 UTC, Mykindos commented
I'd like to do a setting for this, like drop protection & sidebar

2024-06-10 19:14 UTC, manu10000 commented
> I'd like to do a setting for this, like drop protection & sidebar

setting added

2024-06-10 21:01 UTC, Mykindos requested changes

2024-06-10 21:01 UTC, Mykindos commented on core/src/main/java/me/mykindos/betterpvp/core/client/repository/ClientListener.java
> +        Optional<Boolean> cooldownSoundOptional = client.getProperty(ClientProperty.MAP_PLAYER_NAMES);
hmmmmmm...

2024-06-10 21:03 UTC, Mykindos requested changes

2024-06-10 21:03 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/settings/menus/ChampionsSettingsMenu.java
> +}
Cooldowns arent specific to champions, you can just put this in core setting smenu

2024-06-12 07:52 UTC, Mykindos approved these changes

2024-06-12 07:52 UTC, merged