Fix Title Flickering
Mykindos/BetterPvP pull request #898
Opened 2024-06-13 04:07 UTC by StudentAlleg

Fix Title flickering on c home. 

Now flickers if cancels (needs fixing)

Move Delayed Action to title queue

Fixes #861

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested my changes.

2024-06-13 07:10 UTC, StudentAlleg commented
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@31535778
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@31535778), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322)]
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@31535778
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 4 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe)]
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 7 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe)]
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@6b61b9a
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322
[23:45:26] [Craft Scheduler Thread - 8 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] [(500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e), (500,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e5c2e62), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@743de81b), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@4e78322), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@627355fe), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@791df396), (10,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@59d7ede), (9,me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@7f584300)]
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.TitleComponent@47d3ae7e
[23:45:26] [Craft Scheduler Thread - 10 - Core/INFO]: [me.mykindos.betterpvp.core.utilities.model.display.TitleQueue] Next Component is me.mykindos.betterpvp.core.utilities.model.display.Ti [...]

2024-06-13 07:14 UTC, StudentAlleg commented
Looks like PriorityQueue add is not thread safe. An item is added with a higher priority than a current element, but is put at the end of the list (meaning it will be the displayed one), even though it should not be being displayed.
[partiallog.txt](https://github.com/user-attachments/files/15815286/partiallog.txt)

2024-06-13 08:20 UTC, StudentAlleg commented
well I solved the ordering issue, but it now always flashes. Doesnt switch between things though.

2024-06-13 08:20 UTC, StudentAlleg commented
It's a tomorrow problem

2024-06-13 08:28 UTC, Mykindos requested changes

2024-06-13 08:28 UTC, Mykindos commented on clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
> +            UtilMessage.simpleMessage(player, "Clans", "Teleporting to clan home in <green>%s</green> seconds, don't move!", event.getDelayInSeconds());
Make it %.1f

2024-06-14 08:11 UTC, StudentAlleg commented on clans/src/main/java/me/mykindos/betterpvp/clans/clans/listeners/ClansMovementListener.java
> +            UtilMessage.simpleMessage(player, "Clans", "Teleporting to clan home in <green>%s</green> seconds, don't move!", event.getDelayInSeconds());
done

2024-06-14 08:13 UTC, StudentAlleg commented
@Mykindos want you to look over this and the structure before porting this to other queues. This system should be more thread safe, and explicitly define what to do if there are 2 or more elements with the same priority in the queue (uses the one added more recently).

2024-06-14 12:24 UTC, Mykindos approved these changes

2024-06-14 12:24 UTC, merged