Shadow Step
Mykindos/BetterPvP pull request #957
Opened 2024-07-14 15:41 UTC by manu-y

## Describe your changes
Added assassin clone ability. needs actual player testing

## Link to issue (if applicable)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

2024-07-16 01:49 UTC, Mykindos requested changes

2024-07-16 01:49 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
> +    public void onDamageEvent(EntityDamageByEntityEvent event) {
CustomDamageEvent

2024-07-16 14:10 UTC, manu-y commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
> +    public void onDamageEvent(EntityDamageByEntityEvent event) {
done

2024-07-16 14:11 UTC, manu-y commented
tested with polish, balanced it and made the following changes: 
changed AI to Vindicator, made it focus one player if there's player within 16 blocks, gave clone speed 2, made the clone leap forward (like ssm) instead of teleport

2024-07-20 12:20 UTC, Mykindos requested changes

2024-07-20 12:20 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
> +            handleCloneDamage(player, clone);
Why cancel the event if you're just gonna call it again in handleCloneDamage?

You should just be able to override the properties here

2024-07-20 12:20 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
> +    WeakHashMap<Vindicator, Long> clones = new WeakHashMap<>();
private

2024-07-20 12:20 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/warlock/axe/Clone.java
> +        if (!(level > 0)) {
you did not cook with thi sone

if(level <= 0)

2024-07-20 12:20 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/utilities/ClonePathFinder.java
> +    }
You never actually register this listener, so im pretty sure this doesnt work?

2024-07-20 12:20 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/utilities/ClonePathFinder.java
> +    @Inject
You arent injecting anything since you are creating this object yourself

2024-07-20 12:20 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/utilities/ClonePathFinder.java
> +@Singleton
Not really a singleton is it

2024-07-20 12:20 UTC, Mykindos commented on champions/src/main/java/me/mykindos/betterpvp/champions/utilities/ClonePathFinder.java
> +public class ClonePathFinder implements Goal<Mob>, Listener {
Probably shouldn't be a listener, instead handle it in Clone.java

2024-07-23 13:25 UTC, Mykindos approved these changes

2024-07-23 13:25 UTC, merged